[versions]
assertj = '3.27.6'
junit = '5.14.1'
junit-platform = '1.14.1'
lombok = '1.18.42'
maven-publish = '0.35.0'
openrewrite = '2.8.0'
openrewrite-bom = '3.21.0'

[plugins]
openrewrite-recipe-library-base = { id = 'org.openrewrite.build.recipe-library-base', version.ref = 'openrewrite' }
openrewrite-recipe-repositories = { id = 'org.openrewrite.build.recipe-repositories', version.ref = 'openrewrite' }

[libraries]
junit-api = { group = 'org.junit.jupiter', name = 'junit-jupiter-api', version.ref = 'junit' }
junit-params = { group = 'org.junit.jupiter', name = 'junit-jupiter-params', version.ref = 'junit' }
junit-engine = { group = 'org.junit.jupiter', name = 'junit-jupiter-engine', version.ref = 'junit' }
junit-platform-launcher = { group = 'org.junit.platform', name = 'junit-platform-launcher', version.ref = 'junit-platform' }

[bundles]
junit = ['junit-api', 'junit-params', 'junit-engine', 'junit-platform-launcher']
